clone:
  clone:
    image: plugins/git
    tags: true
workspace:
  base: /workdir
  path: code
pipeline:
  tag-the-image:
    image: alpine/git:1.0.4
    pull: false
    commands:
      - echo -n `git describe --tags | sed -e "s/^v//"`",release" > .tags
    when:
      event: tag
  test-compile-and-translate:
    environment:
      - XGOLD_VERSION=${DRONE_TAG##v}
    image: gcr.io/time-coin/gametoken-program-translator:0.4
    pull: true
  package-publish-nuget:
    group: publish
    image: microsoft/dotnet:2-sdk
    environment:
      - XGOLD_VERSION=${DRONE_TAG##v}
    commands:
      - cd /workdir/code
      - dotnet build -c Release
      - dotnet pack -c Release
      - dotnet nuget push bin/Release/Expload.XGold.$XGOLD_VERSION.nupkg -k $NUGET_KEY -s https://api.nuget.org/v3/index.json
    secrets: [ nuget_key ]
    when:
      event: tag
  update-gametoken-program-on-public-node:
    image: gcr.io/time-coin/gametoken-program-updater:0.8
    pull: true
    secrets: [ gametoken_wallet_address, gametoken_wallet_private_key, whitelist ]
    when:
      event: tag
